[package]
name = "synthic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
glob = "0.3"
csbindgen = "1.8.0"

[dependencies]
lerp = "0.5"
rand = "0.8"
itertools = "0.11"
rand_xorshift = "0.3"
